apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: microservicios-cluster
  region: us-east-1

vpc:
  id: vpc-05ca7f776d34ac982
  subnets:
    public:
      us-east-1a:
        id: subnet-03763d9deffc9c095   # ej: subnet-0aaa...
      us-east-1b:
        id: subnet-0fbb2558b7a08e320   # ej: subnet-0bbb...

nodeGroups:
  - name: standard-nodes
    instanceType: t3.micro
    desiredCapacity: 2

